# Site settings
title: Firehose Community
email: code@thefirehoseproject.com
description: > # this means to ignore newlines until "baseurl:"
  The gathering place for all Firehosers to teach, chat, and develop a community that supports each other's growth.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://community.thefirehoseproject.com" # the base hostname & protocol for your site
twitter_username: FirehoseProject
github_username:  FirehoseCommunity
facebook_username: theFirehoseProject
header-img: "img/home-bg.jpg"

# Build settings
markdown: kramdown
port: 3000
host: 0.0.0.0
